version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lab
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql   # <-- mount cả thư mục postgres, không chỉ 'data'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
